version: 2.1
parameters:
  GHA_Event:
    type: string
    default: ""
  GHA_Actor:
    type: string
    default: ""
  GHA_Action:
    type: string
    default: ""
  GHA_Meta:
    type: string
    default: ""
  destroy_review_app:
    type: boolean
    default: false

commands:
  setup:
    description: 'Set up the environment'
    steps:
      - run: echo "Setup on progress"

jobs:
  PRCloseOrMerge:
    docker:
      - image: cimg/node:12.22
    environment:
      BRANCH: << pipeline.git.branch >>
    steps:
      - setup
      - run: echo $BRANCH
      - run: echo ${CIRCLE_BRANCH}
  AnotherJob:
    docker:
      - image: cimg/node:12.22
    steps:
      - setup
      - run:
          name: Echo GHA_Meta
          command: echo ${GHA_Meta}



workflows:
  version: 2
  PRClosedOrMerged:
    when: << pipeline.parameters.destroy_review_app >>
    jobs:
      - AnotherJob
      - PRCloseOrMerge
  OtherWorkflow:
    when:
      not: << pipeline.parameters.destroy_review_app >>
    jobs:
      - AnotherJob