on:
  pull_request:
    types: [ closed ]
jobs:
  trigger-circleci:
    runs-on: ubuntu-latest
    steps:
      - name: Call CircleCI
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.0.4
        env:
          CC_TOKEN: $